### ISSUE TITLE
HTTP service discovery /targets endpoing gives IP addresses with port instead of sysname

### ISSUE THREAD

**Issue by indigo423** [pbrane/PromSNMP#29]
I tried to use the dynmaic service discovery endpoint /targets in Prometheus with the following configuration:

```yaml
  - job_name: "snmp"
    metrics_path: /snmp
    http_sd_configs:
      - url: 'http://scummbar.labmonkeys.tech:8088/targets'
        refresh_interval: 1m
```

The output looks like this:

```json
[ {
  "targets" : [ "192.168.9.4:161" ],
  "labels" : {
    "job" : "snmp",
    "agent_type" : "community",
    "device_name" : "bbone-sw01"
  }
}, {
  "targets" : [ "192.168.9.1:161" ],
  "labels" : {
    "job" : "snmp",
    "agent_type" : "community",
    "device_name" : "spiffy"
  }
}, {
  "targets" : [ "192.168.9.16:161" ],
  "labels" : {
    "job" : "snmp",
    "agent_type" : "community",
    "device_name" : "dinky"
  }
},
.
.
.
```
The problem is, instead of the IP address and port we need the system name (aka device_name) without the port.

The scrape will be now `/metrics?target=192.168.9.4:161` which doesn't work.

Just some food for thoughts, I think we can remove the device_name, agent_type and job from each individual target and just return a list.

The "job" is already defined and the agent_type and device_name don't give us value right now. The output with something like this would be sufficient for now, see https://prometheus.io/docs/prometheus/latest/http_sd/#http_sd-format

```json
[ 
  {
    "targets" : [ "bbone-sw01", "spiffy", ... ]
  } 
]
```
